package id.hivenet.app

data class AppStrings(
    val search: String,
    val settings: String,
    val profile: String,
    val newMessage: String,
    val newGroup: String,
    val addContact: String,
    val encryptedChat: String,
    val localMesh: String,
    val cryptoDebug: String,
    val searchPlaceholder: String,
    val all: String,
    val groups: String,
    val personal: String,
    val settingsSubtitle: String,
    val pageAnimation: String,
    val pageAnimationHint: String,
    val notifications: String,
    val notificationsHint: String,
    val showMessagePreview: String,
    val showMessagePreviewHint: String,
    val sosAlerts: String,
    val sosAlertsHint: String,
    val allowNotifications: String,
    val shortcuts: String,
    val addContactHint: String,
    val localMeshHint: String,
    val securityHint: String,
    val newMessageSubtitle: String,
    val noContactsTitle: String,
    val noContactsHint: String,
)

fun appStringsFor(languageCode: String): AppStrings = if (languageCode.equals("id", ignoreCase = true) || languageCode.equals("in", ignoreCase = true)) {
    AppStrings(
        search = "Cari",
        settings = "Pengaturan",
        profile = "Profil",
        newMessage = "Pesan Baru",
        newGroup = "Grup Baru",
        addContact = "Tambah Kontak",
        encryptedChat = "Chat Terenkripsi",
        localMesh = "Mesh Lokal",
        cryptoDebug = "Debug Kripto",
        searchPlaceholder = "Cari chat atau kontak",
        all = "Semua",
        groups = "Grup",
        personal = "Personal",
        settingsSubtitle = "Perilaku aplikasi dan keamanan",
        pageAnimation = "Animasi halaman",
        pageAnimationHint = "Matikan untuk HP lama agar transisi lebih ringan.",
        notifications = "Notifikasi",
        notificationsHint = "Notifikasi lokal hanya setelah pesan diterima, decrypt sukses, dan tersimpan.",
        showMessagePreview = "Tampilkan pratinjau pesan",
        showMessagePreviewHint = "Matikan kalau tidak mau isi pesan tampil di lock screen.",
        sosAlerts = "Peringatan SOS",
        sosAlertsHint = "Untuk alert darurat lokal setelah paket valid diterima.",
        allowNotifications = "Izinkan Notifikasi",
        shortcuts = "Pintasan",
        addContactHint = "Pairing aman via QR atau token manual",
        localMeshHint = "Start/stop dan cek koneksi mesh lokal",
        securityHint = "Pairing memakai X25519 + HKDF-SHA256. Isi pesan tidak dibackup default. Notif hanya lokal setelah pesan diterima dan tersimpan.",
        newMessageSubtitle = "Pilih kontak untuk mulai chat",
        noContactsTitle = "Belum ada kontak",
        noContactsHint = "Gunakan Tambah Kontak untuk pairing perangkat dulu.",
    )
} else {
    AppStrings(
        search = "Search",
        settings = "Settings",
        profile = "Profile",
        newMessage = "New Message",
        newGroup = "New Group",
        addContact = "Add Contact",
        encryptedChat = "Encrypted Chat",
        localMesh = "Local Mesh",
        cryptoDebug = "Crypto Debug",
        searchPlaceholder = "Search chats or contacts",
        all = "All",
        groups = "Groups",
        personal = "Personal",
        settingsSubtitle = "App behavior and safety",
        pageAnimation = "Page animation",
        pageAnimationHint = "Turn off on older phones for lighter transitions.",
        notifications = "Notifications",
        notificationsHint = "Local notification only after message is received, decrypted, and stored.",
        showMessagePreview = "Show message preview",
        showMessagePreviewHint = "Turn off if you do not want message text on lock screen.",
        sosAlerts = "SOS alerts",
        sosAlertsHint = "For local emergency alerts after valid packets are received.",
        allowNotifications = "Allow Notifications",
        shortcuts = "Shortcuts",
        addContactHint = "Secure pairing via QR or manual token",
        localMeshHint = "Start/stop and check local mesh connection",
        securityHint = "Pairing uses X25519 + HKDF-SHA256. Message bodies are not backed up by default. Notifications are local only after messages are received and stored.",
        newMessageSubtitle = "Pick a contact to start chatting",
        noContactsTitle = "No contacts yet",
        noContactsHint = "Use Add Contact to pair a device first.",
    )
}
